export const ISSUE_STATUS = {
  OPEN: 1,
  IN_PROGRESS: 2,
  RESOLVED: 3,
  CLOSED: 4,
} as const;

export const ISSUE_PRIORITY = {
  LOW: 4,
  NORMAL: 3,
  HIGH: 2,
} as const;

export const NOTIFICATION_REASON = {
  ASSIGNED_TO_ISSUE: 1,
  ISSUE_COMMENTED: 2,
  ISSUE_CREATED: 3,
  ISSUE_UPDATED: 4,
  FILE_ADDED: 5,
  PROJECT_USER_ADDED: 6,
  ASSIGNED_TO_PULL_REQUEST: 10,
  PULL_REQUEST_COMMENTED: 11,
  PULL_REQUEST_CREATED: 12,
  PULL_REQUEST_UPDATED: 13,
} as const;
