name: Icons Check

on:
  push:

jobs:
  icons-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Generate license file
        run: pnpm import-tabler

      - name: Check for license file changes
        run: |
          if [ -n "$(git status --porcelain assets/tabler)" ]; then
            echo "❌ assets/tabler has been modified"
            echo "Please run 'pnpm import-tabler' and commit the changes"
            exit 1
          else
            echo "✅ assets/tabler is up to date"
          fi
