name: License Check

on:
  push:

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate license file
        run: pnpm license

      - name: Check for license file changes
        run: |
          if [ -n "$(git status --porcelain THIRD_PARTY_LICENSES)" ]; then
            echo "❌ THIRD_PARTY_LICENSES has been modified"
            echo "Please run 'npm run license' and commit the changes"
            echo "=== Changes detected ==="
            git diff THIRD_PARTY_LICENSES
            echo "=== End of changes ==="
            exit 1
          else
            echo "✅ THIRD_PARTY_LICENSES is up to date"
          fi
